# Ablation fixture: color_spray
"""Materialized fixture for the color_spray variant of the ablation scene.

Generated by tests/materialize_ablations.py from scripts/ablation_scene.py.
Do not edit by hand -- re-run the generator instead.
"""

from __future__ import annotations

from manim import (
    DOWN,
    LEFT,
    RIGHT,
    Circle,
    Create,
    FadeIn,
    FadeOut,
    RegularPolygon,
    RoundedRectangle,
    Scene,
    Text,
    Transform,
    VGroup,
    config,
    smooth,
)

# --- spec-conformant defaults (../reference/quality-spec.md) -------------------------
BG = "#0E0E10"
FG_TEXT = "#FFFFFF"
BLUE = "#58C4DD"       # generic explanatory accent
GOLD = "#F0AC5F"       # secondary emphasis
GREEN = "#34A853"      # RESERVED: confirmed/success only
FONT = "Roboto"
FILL_OP = 0.12
STROKE_W = 2.5

SPRAY = ["#FF00AA", "#00FFCC", "#FFD400", "#7B2FF7",
         "#FF6B00", "#00A3FF", "#34A853", "#EA4335"]

RUSH = 1.0

config.background_color = BG

# Compound words, used as node labels.
NODE_LABELS = ["LangChain", "Pydantic", "OpenClaw", "Antigravity"]


def rt(x: float) -> float:
    """run_time, scaled by the pacing ablation."""
    return max(0.05, x * RUSH)


def node_color(i: int) -> str:
    return SPRAY[i % len(SPRAY)]


def make_node(label: str, color: str) -> VGroup:
    txt = Text(label, font=FONT, font_size=15, color=color, weight="BOLD")
    body = RoundedRectangle(
        corner_radius=0.22,
        width=max(1.5, txt.width + 0.5), height=0.6,
        fill_color=color, fill_opacity=FILL_OP,
        stroke_color=color, stroke_width=STROKE_W,
    )
    txt.move_to(body.get_center())
    return VGroup(body, txt)


class AblationScene(Scene):
    """~30s clip: nodes appear → travel to issuer → confirmed → caption."""

    def construct(self):
        self.wait(rt(0.8))

        # --- Beat 1: nodes appear -----------------------------------------
        nodes = VGroup(*[
            make_node(l, node_color(i)) for i, l in enumerate(NODE_LABELS)
        ])
        nodes.arrange(DOWN, buff=0.55).move_to(LEFT * 4.0)

        for n in nodes:
            self.play(FadeIn(n, run_time=rt(1.6)))
        self.wait(rt(2.0))

        # --- Beat 2: the issuer -------------------------------------------
        issuer = RegularPolygon(
            n=6, radius=1.15,
            stroke_color=GOLD, stroke_width=STROKE_W,
            fill_color=GOLD, fill_opacity=min(FILL_OP, 0.06),
        ).move_to(RIGHT * 3.6)
        self.play(Create(issuer, run_time=rt(2.0)))
        self.wait(rt(1.5))

        # --- Beat 4: confirmed (reserved GREEN, licensed here only) -------
        badge = Circle(
            radius=0.34, stroke_color=GREEN, stroke_width=STROKE_W,
            fill_color=GREEN, fill_opacity=min(FILL_OP + 0.06, 0.95),
        ).move_to(issuer.get_center())

        self.play(Transform(issuer, badge, run_time=rt(2.0),
                            rate_func=smooth))
        self.wait(rt(2.5))

        # --- Beat 5: single caption, AFTER the visual resolves ------------
        caption = Text("Identity, issued once, at first breath.",
                       font=FONT, font_size=24, color=FG_TEXT)
        caption.move_to(DOWN * 2.6)
        self.play(FadeIn(caption, run_time=rt(1.8)))
        self.wait(rt(3.0))
        tail = caption

        self.play(FadeOut(VGroup(nodes, issuer, tail), run_time=rt(1.5)))
        self.wait(rt(0.8))
